[tool.poetry]
name = "move-forward-and-back"
version = "0.1.0"
description = "A simple interactive terminal game for moving forward and backward."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.13"
windows-curses = "^2.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
